# 基础镜像
FROM nginx
# author
MAINTAINER ruoyi

# 创建目录
# RUN mkdir -p /home/ruoyi/projects/ruoyi-ui
# 指定路径
WORKDIR /home/ruoyi/projects/ruoyi-ui
# 复制conf文件到路径
COPY ./conf.d/default.conf /etc/nginx/conf.d/default.conf
# 复制html文件到路径
COPY ./html/dist /home/ruoyi/projects/ruoyi-ui
# 挂载目录
# VOLUME /home/ruoyi/projects/ruoyi-ui